# Config file for automatic testing at travis-ci.org

language: python
python: 2.7

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install Scrapy docopt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage --cover-package=FourmiCrawler,utils,GUI tests

notifications:
  slack: descartes2:6sgCzx3PvrO9IIMwKxj12dDM

after_success:
  coveralls --verbose
